/*
 jQRangeSlider Copyright (C) Guillaume Gautreau 2010, 2011
 A javascript slider selector that supports dates

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
(function(c){c.widget("ui.rangeSlider",{options:{bounds:{min:0,max:100},defaultValues:{min:20,max:50},wheelMode:null,wheelSpeed:4,arrows:!0,valueLabels:"show",formatter:null,durationIn:0,durationOut:400,delayOut:200},_values:null,bar:null,leftHandle:null,rightHandle:null,innerBar:null,container:null,arrows:null,labels:null,changing:{min:!1,max:!1},changed:{min:!1,max:!1},lastWheel:0,lastScroll:0,scrollCount:0,_create:function(){this._values=this.options.defaultValues;this.labels={left:null,right:null,
leftDisplayed:!0,rightDisplayed:!0};this.arrows={left:null,right:null};this.changing={min:!1,max:!1};this.changed={min:!1,max:!1};this.leftHandle=c("<div class='ui-rangeSlider-handle  ui-rangeSlider-leftHandle' />").draggable({axis:"x",containment:"parent",drag:c.proxy(this._handleMoved,this),stop:c.proxy(this._handleStop,this)}).css("position","absolute");this.rightHandle=c("<div class='ui-rangeSlider-handle ui-rangeSlider-rightHandle' />").draggable({axis:"x",containment:"parent",drag:c.proxy(this._handleMoved,
this),stop:c.proxy(this._handleStop,this)}).css("position","absolute");this.innerBar=c("<div class='ui-rangeSlider-innerBar' />").css("position","absolute").css("top",0).css("left",0);this.container=c("<div class='ui-rangeSlider-container' />").css("position","absolute");this.bar=c("<div class='ui-rangeSlider-bar' />").draggable({axis:"x",drag:c.proxy(this._barMoved,this),stop:c.proxy(this._barStop,this),containment:this.container}).css("position","absolute").bind("mousewheel",c.proxy(this._wheelOnBar,
this));this.arrows.left=c("<div class='ui-rangeSlider-arrow ui-rangeSlider-leftArrow' />").css("position","absolute").css("left",0).bind("mousedown",c.proxy(this._startScrollLeft,this));this.arrows.right=c("<div class='ui-rangeSlider-arrow ui-rangeSlider-rightArrow' />").css("position","absolute").css("right",0).bind("mousedown",c.proxy(this._startScrollRight,this));c(document).bind("mouseup",c.proxy(this._stopScroll,this));this.container.append(this.innerBar).append(this.bar).append(this.leftHandle).append(this.rightHandle);
this.element.append(this.container).append(this.arrows.left).append(this.arrows.right).addClass("ui-rangeSlider").bind("mousewheel",c.proxy(this._wheelOnContainer,this));this.element.css("position")!="absolute"&&this.element.css("position","relative");this.options.arrows?this.element.addClass("ui-rangeSlider-withArrows"):(this.arrows.left.css("display","none"),this.arrows.right.css("display","none"),this.element.addClass("ui-rangeSlider-noArrow"));this.options.valueLabels!="hide"?this._createLabels():
this._destroyLabels();c(window).resize(c.proxy(this.resize,this));this.option(this.options);setTimeout(c.proxy(this.resize,this),1);setTimeout(c.proxy(this._initValues,this),1)},_initWidth:function(){this.container.css("width",this.element.width()-this.container.outerWidth(!0)+this.container.width());this.innerBar.css("width",this.container.width()-this.innerBar.outerWidth(!0)+this.innerBar.width())},_initValues:function(){this.values(this.options.defaultValues.min,this.options.defaultValues.max)},
_setOption:function(a,b){if(a=="defaultValues"){if(typeof b.min!="undefined"&&typeof b.max!="undefined"&&parseFloat(b.min)===b.min&&parseFloat(b.max)===b.max)this.options.defaultValues=b}else if(a=="wheelMode"&&(b=="zoom"||b=="scroll"||b===null))this.options.wheelMode=b;else if(a=="wheelSpeed"&&!isNaN(parseFloat(b))&&Math.abs(parseFloat(b))<=100)this.options.wheelSpeed=parseFloat(b);else if(a=="arrows"&&(b===!0||b===!1)&&b!=this.options.arrows)b?(this.element.removeClass("ui-rangeSlider-noArrow").addClass("ui-rangeSlider-withArrows"),
this.arrows.left.css("display","block"),this.arrows.right.css("display","block")):(this.element.addClass("ui-rangeSlider-noArrow").removeClass("ui-rangeSlider-withArrows"),this.arrows.left.css("display","none"),this.arrows.right.css("display","none")),this.options.arrows=b,this._initWidth(),this._position();else if(a=="valueLabels"&&(b=="hide"||b=="show"||b=="change"))this.options.valueLabels=b,b!="hide"?this._createLabels():this._destroyLabels();else if(a=="formatter"&&b!==null&&typeof b=="function")this.options.formatter=
b,this._position();else if(a=="bounds"&&typeof b.min!="undefined"&&typeof b.max!="undefined"&&parseFloat(b.min)===b.min&&parseFloat(b.max)===b.max&&b.min<b.max)this.options.bounds=b,this.values(this._values.min,this._values.max)},_getPosition:function(a){return(a-this.options.bounds.min)*(this.container.innerWidth()-1)/(this.options.bounds.max-this.options.bounds.min)},_getValue:function(a){return a*(this.options.bounds.max-this.options.bounds.min)/(this.container.innerWidth()-1)+this.options.bounds.min},
_privateValues:function(a,b){this._setValues(a,b);this._position();return this._values},_trigger:function(a){this.element.trigger(a,{label:this.element,values:this.values()})},_position:function(){var a=this._getPosition(this._values.min),b=this._getPosition(this._values.max);this._positionHandles();this.bar.css("left",a).css("width",b-a+this.bar.width()-this.bar.outerWidth(!0)+1)},_positionHandles:function(){var a=this._getPosition(this._values.min),b=this._getPosition(this._values.max)-this.rightHandle.outerWidth(!0)+
1;this.leftHandle.css("left",a);this.rightHandle.css("left",b);this._positionLabels()},_barMoved:function(a,b){var c=b.position.left,d=c+this.bar.outerWidth(!0)-1;this._setValues(this._getValue(c),this._getValue(d));this._positionHandles()},_barStop:function(){this._position();this._prepareFiringChanged()},_switchHandles:function(){var a=this.leftHandle;this.leftHandle=this.rightHandle;this.rightHandle=a;this.leftHandle.removeClass("ui-rangeSlider-rightHandle").addClass("ui-rangeSlider-leftHandle");
this.rightHandle.addClass("ui-rangeSlider-rightHandle").removeClass("ui-rangeSlider-leftHandle")},_handleMoved:function(a,b){var c=this._values.min,d=this._values.max;if(b.helper[0]==this.leftHandle[0])c=this._getValue(b.position.left);else if(b.helper[0]==this.rightHandle[0])d=this._getValue(b.position.left-1+b.helper.outerWidth(!0));else return;if(c>d){this._switchHandles();var e=c,c=d,d=e}this._privateValues(c,d)},_handleStop:function(){this._position();this._prepareFiringChanged()},_changing:function(a,
b){this._trigger("valuesChanging");var c=!1;if(a&&!this.changing.min)this._trigger("minValueChanging"),c=this.changing.min=!0;if(b&&!this.changing.max)this._trigger("maxValueChanging"),c=this.changing.max=!0;c&&this._showLabels()},_prepareFiringChanged:function(){var a=this.lastWheel=Math.random();setTimeout(c.proxy(function(){this._fireChanged(a)},this),200)},_fireChanged:function(a){if(this.lastWheel==a&&!this.bar.hasClass("ui-draggable-dragging")&&!this.leftHandle.hasClass("ui-draggable-dragging")&&
!this.rightHandle.hasClass("ui-draggable-dragging")){a=!1;if(this.changing.min)this.changing.min=!1,this._trigger("minValueChanged"),a=!0;if(this.changing.max)this.changing.max=!1,this._trigger("maxValueChanged"),a=!0;a&&this._trigger("valuesChanged");this._hideLabels()}},_setValuesHandles:function(a,b){this._setValues(a,b);this._positionHandles()},_setValues:function(a,b){var c=this._values,d=Math.abs(b-a);if(d>=this.options.bounds.max-this.options.bounds.min)this._values.min=this.options.bounds.min,
this._values.max=this.options.bounds.max;else{var e={min:Math.min(b,a),max:Math.max(a,b)};if(e.min<this.options.bounds.min)e.min=this.options.bounds.min,e.max=e.min+d;else if(e.max>this.options.bounds.max)e.max=this.options.bounds.max,e.min=e.max-d;this._values=e}this._changing(c.min!=this._values.min,c.max!=this._values.max);this._prepareFiringChanged()},_startScrollLeft:function(){this.lastScroll=Math.random();this.scrollCount=0;this._continueScrollingRight(-1,this.lastScroll)},_startScrollRight:function(){this.lastScroll=
Math.random();this.scrollCount=0;this._continueScrollingRight(1,this.lastScroll)},_continueScrollingRight:function(a,b){b==this.lastScroll&&(this.scrollRight(a*(Math.min(Math.floor(this.scrollCount/5)+1,4)/4)),this.scrollCount++,setTimeout(c.proxy(function(){this._continueScrollingRight(a,b)},this),50))},_stopScroll:function(){this.lastScroll=Math.random()},_wheelOnBar:function(a,b,c,d){if(this.options.wheelMode=="zoom")return this.zoomIn(-d),!1},_wheelOnContainer:function(a,b,c,d){if(this.options.wheelMode==
"scroll")return this.scrollRight(-d),!1},_createLabel:function(a,b){a===null&&(a=c("<div class='ui-rangeSlider-label'/>").addClass(b).css("position","absolute"),this.element.append(a),this._positionLabels());return a},_destroyLabel:function(a){a!==null&&(a.remove(),a=null);return a},_createLabels:function(){this.labels.left=this._createLabel(this.labels.left,"ui-rangeSlider-leftLabel");this.labels.right=this._createLabel(this.labels.right,"ui-rangeSlider-rightLabel");this.options.valueLabels=="change"?
(this.labels.left.css("display","none"),this.labels.right.css("display","none"),this.labels.leftDisplayed=!1,this.labels.rightDisplayed=!1):(this.labels.leftDisplayed=!0,this.labels.rightDisplayed=!0,this.labels.left.css("display","block"),this.labels.right.css("display","block"),this._position())},_destroyLabels:function(){this.labels.left=this._destroyLabel(this.labels.left);this.labels.right=this._destroyLabel(this.labels.right)},_positionLabel:function(a,b){var c=this.leftHandle.offset().top-
a.outerHeight(!0),d=a.offsetParent(),e=b-d.offset().left;c-=d.offset().top;a.css("left",e).css("top",c)},_positionLabels:function(){if(this.labels.left!==null&&this.labels.right!==null){this.labels.left.text(this._format(this._values.min));this.labels.right.text(this._format(this._values.max));var a=this.labels.leftDisplayed?this.labels.left.outerWidth(!0):0,b=this.labels.rightDisplayed?this.labels.right.outerWidth(!0):0,f=c(window).width()-b,d=Math.max(0,this.leftHandle.offset().left+this.leftHandle.outerWidth(!0)/
2-a/2),b=Math.min(f,this.rightHandle.offset().left+this.rightHandle.outerWidth(!0)/2-b/2);d+a>=b&&(d=Math.max(0,d-(d+a-b)/2),b=Math.min(f,d+a),d=Math.max(0,b-a));this.labels.leftDisplayed&&this._positionLabel(this.labels.left,d);this.labels.rightDisplayed&&this._positionLabel(this.labels.right,b)}},_format:function(a){return typeof this.options.formatter!="undefined"&&this.options.formatter!==null?this.options.formatter(a):this._defaultFormat(a)},_defaultFormat:function(a){return Math.round(a)},_showLabels:function(){if(this.options.valueLabels==
"change"&&!this.privateChange){if(this.changing.min&&!this.labels.leftDisplayed)this.labels.left.stop(!0,!0).fadeIn(this.options.durationIn),this.labels.leftDisplayed=!0;if(this.changing.max&&!this.labels.rightDisplayed)this.labels.rightDisplayed=!0,this.labels.right.stop(!0,!0).fadeIn(this.options.durationIn)}},_hideLabels:function(){if(this.options.valueLabels=="change"&&this.labels.left!==null&&this.labels.right!==null)this.labels.leftDisplayed=!1,this.labels.rightDisplayed=!1,this.labels.left.stop(!0,
!0).delay(this.options.delayOut).fadeOut(this.options.durationOut),this.labels.right.stop(!0,!0).delay(this.options.delayOut).fadeOut(this.options.durationOut)},values:function(a,b){if(typeof a!="undefined"&&typeof b!="undefined")this.internalChange=!1,this._privateValues(a,b),this.internalChange=!0;return this._values},min:function(a){return this.values(a,this._values.max).min},max:function(a){return this.values(this._values.min,a).max},zoomIn:function(a){var b=this._values.max-this._values.min;
this._privateValues(this._values.min+a*this.options.wheelSpeed*b/200,this._values.max-a*this.options.wheelSpeed*b/200)},zoomOut:function(a){this.zoomIn(-a)},scrollLeft:function(a){typeof a=="undefined"&&(a=1);this.scrollRight(-a)},scrollRight:function(a){typeof a=="undefined"&&(a=1);var b=this._values.max-this._values.min;this._privateValues(this._values.min+a*this.options.wheelSpeed*b/100,this._values.max+a*this.options.wheelSpeed*b/100)},resize:function(){this._initWidth();this._position()},destroy:function(){this.element.removeClass("ui-rangeSlider-withArrows").removeClass("ui-rangeSlider-noArrow");
this.bar.detach();this.leftHandle.detach();this.rightHandle.detach();this.innerBar.detach();this.container.detach();this.arrows.left.detach();this.arrows.right.detach();this.element.removeClass("ui-rangeSlider");this._destroyLabels();delete this.options;c.Widget.prototype.destroy.apply(this,arguments)}})})(jQuery);
